# Continuous integration configuration file, used by Jenkins
# Author: Chris Zalidis, Konstantinos Sideris
install:
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros python-pip
  - sudo pip install pandoradep
  - sudo rosdep init
  - rosdep update

  # Create workspace
  - mkdir -p $BUILD_HOME/catkin_ws/src
  - cp -r $BUILD_HOME/$REPOSITORY_NAME $BUILD_HOME/catkin_ws/src
  - cd $BUILD_HOME/catkin_ws/src

  # Find and download PANDORA dependencies
  - pandoradep fetch

  - wstool init .
  - wstool update

  - cd ..

  # Install debian dependencies
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -q -y
  - source /opt/ros/$ROS_DISTRO/setup.bash
script:
  # All commands must exit with code 0 on success.
  # Anything else is considered failure.
  - catkin_make --only-pkg-with-deps $REPOSITORY_NAME
  - source devel/setup.bash
  - catkin_make roslint_pandora_costmap
