#ifndef TARGET_SELECTOR_CONTROLLER_DEFINES_H
#define TARGET_SELECTOR_CONTROLLER_DEFINES_H

	//~ #define CLOSEST_UNEXPLORED
	#define SIMPLE_EXPLORATION
	//~ #define EXPLORATION_GAUSSIAN_EXCLUSION
	//~ #define EXPLORATION_GAUSSIAN_EXCLUSION_NEW_WEIGHTS


#endif

